### ISSUE TITLE
Feature request, add stream writer support 请问一下有考虑支持流式写入的功能吗？

### ISSUE THREAD

**Issue by logdd** [xuri/excelize-wasm#18]
因为导入大量数据会导致内存占用高，请问下是否考虑对流式写入的支持？

**Comment by xuri** [comment]
Thanks for your issue. There is no plan to add stream writer support in the WebAssembly version, please use the Go version. I've closed this, if you have any questions, please let me know, and reopen this anytime.

谢谢你的问题，目前没有计划在 WebAssembly 版本中添加流编写器支持，请使用 Go 版本。我已将此问题关闭，如果你有任何问题，请告诉我，然后随时重新打开。
