### ISSUE TITLE
Is it possible to format cells?

### ISSUE THREAD

**Issue by riziles** [xuri/excelize-wasm#20]
Just curious if the WASM port allows cell formatting.

**Comment by xuri** [comment]
Yes. Please create style by the NewStyle function at first, and set cell style with the SetCellStyle function, just like using the Excelize library.

**Comment by riziles** [comment]
> Yes. Please create style by the NewStyle function at first, and set cell style with the SetCellStyle function, just like using the Excelize library.

Thanks! I got a working example going here: https://stackblitz.com/edit/web-platform-swx4rl

**Comment by riziles** [comment]
Closing this as completed because it works and is awesome. I would recommend adding a format example to the README file.
