### ISSUE TITLE
expose GetSheetDimension

### ISSUE THREAD

**Issue by stephen-dahl** [xuri/excelize-wasm#33]
Please expose these functions. They do not show up on the list of available functions in TS
SetSheetDimension
GetSheetDimension
https://xuri.me/excelize/en/sheet.html#SetSheetDimension

<img width="717" alt="image" src="https://github.com/user-attachments/assets/f1bd5308-ded6-4ca1-a799-2786933bd85e">

**Comment by xuri** [comment]
Thanks for your issue. I added support for this, and this feature will be released in the next version.
